### ISSUE TITLE
fix(mediaviewer): meta defaults

### ISSUE THREAD

**Issue by eoaksnes** [equinor/dm-core-packages#1223]
- [x] don't show the "Description" label in the meta box
- [x] configure show "info" (i) button
- [x] don't show title in meta should be "figure" not "Meta"
