### ISSUE TITLE
feat: improve list plugins

### ISSUE THREAD

**Issue by eoaksnes** [equinor/dm-core-packages#414]
List plugin
- [x] Remove table markup
- [x] Map from objects to array instead of mapping from objects to objects with array values
- [x] Fix plugin crash when trying to read attribute from data that isn't an object
- [x] Add option to open in new tab
- [x] Add config to allow user to select between open in new tab or inline
- [x] Switch out with dm-core pagination
- [ ] Use label when available, if not available use name.
- [x] When you submit the form, two instances are stored. Same happens when you edit an item.
- [x] Fix bug with pagination: If you add enough items so that pagination becomes active, you can now paginate beyond the number of items in the table.
- [x] Add pagination button titles @roar-larsen #366
- [x] Add title to expand-minimize button @roar-larsen #371
- [x] Add correct titles to list item buttons @roar-larsen #375

**Comment by henrikbossart** [comment]
> Use label when available, if not use name.

Which label is there talk about here? And where is a label supposed to be shown? 🤔

**Comment by soofstad** [comment]
Close it @roar-larsen?

**Comment by roar-larsen** [comment]
Yes, I think the label issue has been addressed somewhere else. At least I don´t see any obvious places where this is missing. Closing.
